### ISSUE TITLE
Cannot play *.avi file (see attachment)

### ISSUE THREAD

**Issue by usilitel** [dburckh/Media3Avi#3]
I added the media3-avi library to my project. It plays most of *.avi files, except one (I attached it to this issue).

[breakdance.avi.zip](https://github.com/dburckh/Media3Avi/files/10277076/breakdance.avi.zip)

**Comment by dburckh** [comment]
Thanks for including the file.  I'll have a look at it and see if I can fix it.  It may be a week or so because I'm travelling.

**Comment by dburckh** [comment]
This AVI file has a leading chunk of zeros in the MP3 stream.  Some decoders ignored it, but the Pixel decoder was crashing.  I'm now dumping non-MP3 data and advancing the clock if the chunk has no MP3 data.  I AssUMe this was the muxer's intent.  I'm also advancing the clock on zero length chunks.

This change has been pushed as part of tag 2.2.  @usilitel Please confirm the fix and close the issue.

**Comment by usilitel** [comment]
May be I am doing something wrong, but in tag 2.2 I see only changes in file README.md:

![изображение](https://user-images.githubusercontent.com/25177578/209499621-8c46b06d-9644-45c7-94f9-c2d0a5afc7e5.png)

**Comment by usilitel** [comment]
Yes, now this file is playing. Everything works fine. Thank you.
