### ISSUE TITLE
Publish using Jitpack

### ISSUE THREAD

**Issue by TheBeastLT** [dburckh/Media3Avi#7]
I'd suggest using Jitpack to publish the artifact instead of Github repository, as there you don't need credentials and it's quite easy to setup.

**Comment by dburckh** [comment]
Cool.  I'll have a look at that.  I looked briefly at publishing to Central with Apache.

**Comment by dburckh** [comment]
Jitpack.io is pretty slick.  I'll be converting all my projects over.  

Thank you for giving me a push in the right direction!  I still need to figure out how to get the tests to show up, but the no-cred hosting  and not building artifacts on my machine are already a huge improvements.

Implemented in 2.3.0.
